# SELinux
BOARD_SEPOLICY_DIRS := \
       $(DEVICE_DIR)/sepolicy

BOARD_SEPOLICY_UNION := \
	aal.te \
	adbd.te \
	aee_core_forwarder.te \
	af7133e.te \
	akmd09911.te \
	akmd8963.te \
	akmd8975.te \
	ami304d.te \
	app.te \
	atcid.te \
	atci_service.te \
	attributes \
	audiocmdservice_atci.te \
	autokd.te \
	batterywarning.te \
	BGW.te \
	bluetooth.te \
	bmc156d.te \
	bmm050d.te \
	bmm056d.te \
	bmx056d.te \
	bootanim.te \
	boot_logo_updater.te \
	br_app_data_service.te \
	ccci_fsd.te \
	ccci_mdinit.te \
	ccci_rpcd.te \
	clatd.te \
	cmddumper.te \
	device.te \
	dex2oat.te \
	dhcp6c.te \
	dhcp.te \
	disableswap.te \
	dm_agent_binder.te \
	dmlog.te \
	dnsmasq.te \
	domain.te \
	drmserver.te \
	dualmdlogger.te \
	dumpstate.te \
	eemcs_fsd.te \
	eemcs_mdinit.te \
	emdlogger.te \
	em_svr.te \
	enableswap.te \
	epdg_wod.te \
	factory.te \
	file_contexts \
	file.te \
	flashlessd.te \
	fota1.te \
	fs_use \
	fuelgauged.te \
	genfs_contexts \
	geomagneticd.te \
	GoogleOtaBinder.te \
	gpsd.te \
	gsm0710muxdmd2.te \
	gsm0710muxd.te \
	guiext-server.te \
	hci_attach.te \
	healthd.te \
	hostapd.te \
	icusbd.te \
	init_shell.te \
	init.te \
	inputflinger.te \
	installd.te \
	install_recovery.te \
	ipod.te \
	ipsec.te \
	isolated_app.te \
	ist8303.te \
	kernel.te \
	keystore.te \
	kisd.te \
	launchpppoe.te \
	lmkd.te \
	logd.te \
	matv.te \
	mc6420d.te \
	mc6470d.te \
	md_ctrl.te \
	mdlogger.te \
	mdnsd.te \
	mediaserver.te \
	memsicd3416x.te \
	memsicd.te \
	memsicp.te \
	meta_tst.te \
	mmc3524xd.te \
	mmc_ffu.te \
	mmp.te \
	mnld.te \
	mobicore.te \
	mobile_log_d.te \
	mpud6050.te \
	msensord.te \
	mtee.te \
	mtk_6620_launcher.te \
	mtk_agpsd.te \
	mtkbt.te \
	MtkCodecService.te \
	mtk_file.te \
	mtkrildmd2.te \
	mtkrild.te \
	mtp.te \
	muxreport.te \
	netdiag.te \
	netd.te \
	net.te \
	nfc.te \
	nvram_agent_binder.te \
	nvram_backup_binder.te \
	nvram_daemon.te \
	orientationd.te \
	permission_check.te \
	platform_app.te \
	poad.te \
	ppl_agent.te \
	pppd_dt.te \
	pppd_via.te \
	ppp.te \
	pq.te \
	program_binary.te \
	property_contexts \
	property.te \
	pvrsrvctl.te \
	qmcX983d.te \
	racoon.te \
	radio.te \
	recovery.te \
	resmon.te \
	ril-3gddaemon.te \
	rild.te \
	runas.te \
	s62xd.te \
	sbchk.te \
	sdcardd.te \
	service_contexts \
	servicemanager.te \
	service.te \
	shared_relro.te \
	shell.te \
	sn.te \
	st480.te \
	statusd.te \
	surfaceflinger.te \
	system_app.te \
	system_server.te \
	tee.te \
	te_macros \
	terservice.te \
	thermald.te \
	thermal_manager.te \
	thermal.te \
	tiny_mkswap.te \
	tiny_swapon.te \
	tunman.te \
	ueventd.te \
	uncrypt.te \
	untrusted_app.te \
	usbdongled.te \
	vdc.te \
	viarild.te \
	vold.te \
	volte_imcb.te \
	volte_stack.te \
	volte_ua.te \
	vtservice.te \
	watchdogd.te \
	wifi2agps.te \
	wmt_loader.te \
	wpa_supplicant.te \
	wpa.te \
	xlog.te \
	zpppd_gprs.te \
	zygote.te \
